version: '3'

services:
  database:
    build: ./database
    # Дополнительные настройки для базы данных

  server:
    build: ./server
    # Дополнительные настройки для сервера

  user:
    build: ./user
    ports:
      - "500:9050"
    # Дополнительные настройки для фронтенда
